org: wildmint
app: teleport
service: teleport
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  stage: production # Set the default stage used. Default is dev
  region: us-east-1 # Overwrite the default region used. Default is us-east-1
  memorySize: 512
  websocketsApiName: teleport-ws
  websocketsApiRouteSelectionExpression: $request.body.action
  websocketsDescription: teleport-chat-application

  iam:
    # name: teleport
    role: arn:aws:iam::245513588317:role/teleport


plugins:
  - serverless-offline
functions:
  connectHandler:
    handler: src/functions/connect.connectHandler
    events:
      - websocket:
          route: $connect
  disconnectHandler:
    handler: src/functions/disconnect.disconnectHandler
    events:
      - websocket:
          route: $disconnect

  sayHelloHandler:
    handler: src/functions/default.defaultHandler
    events:
      - websocket:
          route: $default
  sendMessageHandler:
    handler: src/functions/sendMessage.sendMessageHandler
    events:
      - websocket:
          route: sendmsg
  create:
    handler: src/functions/user.createUserHandler
    events:
      - http:
          path: /user
          method: post
  delete:
    handler: src/functions/user.deleteUserHandler
    events:
      - http:
          path: /user/{id}
          method: delete
  update:
    handler: src/functions/user.updateUserHandler
    events:
      - http:
          path: /user/{id}
          method: patch
  get:
    handler: src/functions/user.getUserHandler
    events:
      - http:
          path: /user/{id}
          method: get
resources:
  Resources:
    usersTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: usersTable
        KeySchema:
          - AttributeName: connectionId
            KeyType: HASH
        AttributeDefinitions:
          - AttributeName: connectionId
            AttributeType: S
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
