name: Teleport CI
run-name: ${{ github.actor }}

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'
      - run: npm ci
      - name: Build the task
        run: docker-compose up -d
      - run: npm run build --if-present
      - run: npm test
      - run: npm run test -- --runInBand
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: test-results
          path: reports/jest-junit.xml
          reporter: jest-junit
      - name: Docker status on failure
        run: docker-compose ps && docker-compose logs -t
        if: failure()
