name:  CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          # cache: "npm"
      - run: npm ci
      - run: npm run lint
      - name: Build the stack
        run: docker-compose up -d
      - run: npm run test -- --runInBand
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: test-results
          path: reports/jest-junit.xml
          reporter: jest-junit
      - name: Docker status on failure
        run: docker-compose ps && docker-compose logs -t
        if: failure()
